import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
 title: 'Créez un QR code. Connectez une fois. Gardez-le à jour. | Mioseg QR', description: 'Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.',
 alternates: { canonical: '/fr/generateur-qr-code', languages: { "de-DE": '/de/qr-code-generator', "fr": '/fr/generateur-qr-code', "x-default": "/en/qr-code-generator" } },
 openGraph: { title: 'Créez un QR code. Connectez une fois. Gardez-le à jour. | Mioseg QR', description: 'Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.', url: '/fr/generateur-qr-code', type:"website" }
};

const faq=[{q:"Qu'est-ce qu'un QR code dynamique ?",a:"C'est un QR code dont le contenu associé peut être mis à jour plus tard sans remplacer le code lui-même."},{q:'Puis-je créer mes propres QR codes ?',a:'Oui. Mioseg QR permet de créer vos propres QR codes dynamiques.'}];
const points=['Créer','Ajouter du contenu','Utiliser le QR','Mettre à jour'];

export default function Page(){
 const jsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))};
 return <main className="locSeoPage">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="locSeoHero"><div className="locSeoWrap locSeoHeroGrid"><div><span className="locSeoEyebrow">GÉNÉRATEUR QR CODE</span><h1>Créez un QR code. Connectez une fois. Gardez-le à jour.</h1><p className="locSeoLead">Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.</p><div className="locSeoActions"><Link href="/fr/get-app" className="locSeoPrimary">Commencer</Link><Link href="/fr/aide" className="locSeoSecondary">Centre d’aide</Link></div></div><div className="locSeoMock"><div className="locSeoQr">▦</div><h3>Mioseg QR</h3><p>Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.</p></div></div></section>
  <section className="locSeoSection"><div className="locSeoHead"><span className="locSeoEyebrow" style={{color:"#2867e8"}}>MIOSEG QR</span><h2>Créez une fois. Gérez le contenu ensuite.</h2></div><div className="locSeoGrid">{points.map((p,i)=><article key={p}><b>{String(i+1).padStart(2,"0")}</b><h3>{p}</h3><p>Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.</p></article>)}</div></section>
  <section className="locSeoDark"><span className="locSeoEyebrow">MIOSEG QR</span><h2>Créez un QR code. Connectez une fois. Gardez-le à jour.</h2><p>Créez vos propres Mioseg QR dynamiques pour des objets, lieux, produits ou projets et mettez leur contenu à jour ultérieurement.</p></section>
  <section className="locSeoSection"><div className="locSeoHead"><span className="locSeoEyebrow" style={{color:"#2867e8"}}>Questions fréquentes</span><h2>Questions fréquentes</h2></div><div className="locSeoFaq">{faq.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section>
  <section className="locSeoFinal"><span className="locSeoEyebrow">MIOSEG QR</span><h2>Découvrir Mioseg QR</h2><div className="locSeoActions"><Link href="/fr/get-app" className="locSeoPrimary">Commencer</Link><Link href="/fr/aide" className="locSeoSecondary">Centre d’aide</Link></div></section>
  <style>{`
*{box-sizing:border-box}.locSeoPage{min-height:100vh;background:#f5f8fc;color:#0a1930;font-family:Inter,system-ui,-apple-system,sans-serif}.locSeoHero{background:radial-gradient(circle at 78% 35%,#17366b 0,#0c2346 22%,#071426 52%);color:#fff;padding:78px 24px 90px}.locSeoWrap{width:min(1160px,100%);margin:auto}.locSeoHeroGrid{display:grid;grid-template-columns:1.08fr .72fr;gap:75px;align-items:center}.locSeoEyebrow{font-size:12px;letter-spacing:.12em;font-weight:850;color:#82aaff}.locSeoHero h1{font-size:clamp(42px,6vw,68px);line-height:1.04;letter-spacing:-.04em;margin:15px 0 24px}.locSeoLead{font-size:19px;line-height:1.7;color:#bdc9da}.locSeoActions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.locSeoPrimary,.locSeoSecondary{padding:14px 20px;border-radius:12px;text-decoration:none;font-weight:800}.locSeoPrimary{background:#fff;color:#0b1d37}.locSeoSecondary{border:1px solid #496487;color:#e2e9f4}.locSeoMock{background:#fff;color:#10213a;border-radius:26px;padding:25px;box-shadow:0 30px 80px #0007}.locSeoQr{height:190px;background:#edf3fb;border-radius:20px;display:grid;place-items:center;font-size:90px;color:#2867e8}.locSeoMock p{color:#687990;line-height:1.6}.locSeoSection{width:min(1160px,calc(100% - 36px));margin:90px auto}.locSeoHead{text-align:center;max-width:790px;margin:0 auto 38px}.locSeoHead h2{font-size:clamp(31px,4vw,48px);line-height:1.1;letter-spacing:-.03em;margin:12px 0}.locSeoGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.locSeoGrid article{background:#fff;border:1px solid #e1e8f1;border-radius:20px;padding:25px}.locSeoGrid b{display:block;color:#2867e8;font-size:13px;margin-bottom:12px}.locSeoGrid h3{margin:0 0 8px}.locSeoGrid p{color:#687990;line-height:1.6;font-size:14px}.locSeoDark{background:#071426;color:#fff;padding:80px 24px;text-align:center}.locSeoDark h2{font-size:clamp(31px,4vw,48px);max-width:850px;margin:12px auto}.locSeoDark p{max-width:760px;margin:18px auto;color:#b7c5d9;line-height:1.7}.locSeoFaq{max-width:850px;margin:auto;display:grid;gap:10px}.locSeoFaq details{background:#fff;border:1px solid #e1e8f1;border-radius:15px;padding:0 20px}.locSeoFaq summary{cursor:pointer;list-style:none;padding:20px 0;font-weight:800;display:flex;justify-content:space-between;gap:20px}.locSeoFaq p{color:#607188;line-height:1.7;padding:0 0 20px;margin:0}.locSeoFinal{background:#0a1930;color:#fff;text-align:center;padding:75px 24px}.locSeoFinal h2{font-size:clamp(34px,5vw,52px);margin:12px}.locSeoFinal .locSeoActions{justify-content:center}@media(max-width:850px){.locSeoHeroGrid{grid-template-columns:1fr}.locSeoGrid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.locSeoHero{padding:58px 24px}.locSeoHero h1{font-size:41px}.locSeoGrid{grid-template-columns:1fr}.locSeoSection{margin:65px auto}}
`}</style>
 </main>
}
