import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
 title: 'QR kod aynı kalır. Bilgiler gelişebilir. | Mioseg QR', description: 'Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.',
 alternates: { canonical: '/tr/dinamik-qr-kod', languages: { "de-DE": '/de/dynamischer-qr-code', "tr": '/tr/dinamik-qr-kod', "x-default": "/en/dynamic-qr-code" } },
 openGraph: { title: 'QR kod aynı kalır. Bilgiler gelişebilir. | Mioseg QR', description: 'Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.', url: '/tr/dinamik-qr-kod', type:"website" }
};

const faq=[{q:'QR kod güncellemeden sonra değişir mi?',a:"Hayır. Mioseg QR'da bağlı içerik güncellenirken mevcut QR kodu kullanılmaya devam edebilir."},{q:'Ne zaman kullanışlıdır?',a:'Bilgilerin QR kod basıldıktan veya yerleştirildikten sonra değişebileceği durumlarda kullanışlıdır.'}];
const points=['QR kod kalır','Bağlantı yönetilir','İçerik güncellenir'];

export default function Page(){
 const jsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))};
 return <main className="locSeoPage">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="locSeoHero"><div className="locSeoWrap locSeoHeroGrid"><div><span className="locSeoEyebrow">DİNAMİK QR KOD</span><h1>QR kod aynı kalır. Bilgiler gelişebilir.</h1><p className="locSeoLead">Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.</p><div className="locSeoActions"><Link href="/tr/get-app" className="locSeoPrimary">Başla</Link><Link href="/tr/yardim" className="locSeoSecondary">Yardım Merkezi</Link></div></div><div className="locSeoMock"><div className="locSeoQr">▦</div><h3>Mioseg QR</h3><p>Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.</p></div></div></section>
  <section className="locSeoSection"><div className="locSeoHead"><span className="locSeoEyebrow" style={{color:"#2867e8"}}>MIOSEG QR</span><h2>“Dinamik” QR kod ne demektir?</h2></div><div className="locSeoGrid">{points.map((p,i)=><article key={p}><b>{String(i+1).padStart(2,"0")}</b><h3>{p}</h3><p>Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.</p></article>)}</div></section>
  <section className="locSeoDark"><span className="locSeoEyebrow">MIOSEG QR</span><h2>QR kod aynı kalır. Bilgiler gelişebilir.</h2><p>Bilgiler değişse bile aynı QR kodunu kullanmaya devam et. Mioseg QR ile bağlı dijital içerikleri sonradan güncelleyebilirsin.</p></section>
  <section className="locSeoSection"><div className="locSeoHead"><span className="locSeoEyebrow" style={{color:"#2867e8"}}>Sık sorulan sorular</span><h2>Sık sorulan sorular</h2></div><div className="locSeoFaq">{faq.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section>
  <section className="locSeoFinal"><span className="locSeoEyebrow">MIOSEG QR</span><h2>Mioseg QR’ı keşfet</h2><div className="locSeoActions"><Link href="/tr/get-app" className="locSeoPrimary">Başla</Link><Link href="/tr/yardim" className="locSeoSecondary">Yardım Merkezi</Link></div></section>
  <style>{`
*{box-sizing:border-box}.locSeoPage{min-height:100vh;background:#f5f8fc;color:#0a1930;font-family:Inter,system-ui,-apple-system,sans-serif}.locSeoHero{background:radial-gradient(circle at 78% 35%,#17366b 0,#0c2346 22%,#071426 52%);color:#fff;padding:78px 24px 90px}.locSeoWrap{width:min(1160px,100%);margin:auto}.locSeoHeroGrid{display:grid;grid-template-columns:1.08fr .72fr;gap:75px;align-items:center}.locSeoEyebrow{font-size:12px;letter-spacing:.12em;font-weight:850;color:#82aaff}.locSeoHero h1{font-size:clamp(42px,6vw,68px);line-height:1.04;letter-spacing:-.04em;margin:15px 0 24px}.locSeoLead{font-size:19px;line-height:1.7;color:#bdc9da}.locSeoActions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.locSeoPrimary,.locSeoSecondary{padding:14px 20px;border-radius:12px;text-decoration:none;font-weight:800}.locSeoPrimary{background:#fff;color:#0b1d37}.locSeoSecondary{border:1px solid #496487;color:#e2e9f4}.locSeoMock{background:#fff;color:#10213a;border-radius:26px;padding:25px;box-shadow:0 30px 80px #0007}.locSeoQr{height:190px;background:#edf3fb;border-radius:20px;display:grid;place-items:center;font-size:90px;color:#2867e8}.locSeoMock p{color:#687990;line-height:1.6}.locSeoSection{width:min(1160px,calc(100% - 36px));margin:90px auto}.locSeoHead{text-align:center;max-width:790px;margin:0 auto 38px}.locSeoHead h2{font-size:clamp(31px,4vw,48px);line-height:1.1;letter-spacing:-.03em;margin:12px 0}.locSeoGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.locSeoGrid article{background:#fff;border:1px solid #e1e8f1;border-radius:20px;padding:25px}.locSeoGrid b{display:block;color:#2867e8;font-size:13px;margin-bottom:12px}.locSeoGrid h3{margin:0 0 8px}.locSeoGrid p{color:#687990;line-height:1.6;font-size:14px}.locSeoDark{background:#071426;color:#fff;padding:80px 24px;text-align:center}.locSeoDark h2{font-size:clamp(31px,4vw,48px);max-width:850px;margin:12px auto}.locSeoDark p{max-width:760px;margin:18px auto;color:#b7c5d9;line-height:1.7}.locSeoFaq{max-width:850px;margin:auto;display:grid;gap:10px}.locSeoFaq details{background:#fff;border:1px solid #e1e8f1;border-radius:15px;padding:0 20px}.locSeoFaq summary{cursor:pointer;list-style:none;padding:20px 0;font-weight:800;display:flex;justify-content:space-between;gap:20px}.locSeoFaq p{color:#607188;line-height:1.7;padding:0 0 20px;margin:0}.locSeoFinal{background:#0a1930;color:#fff;text-align:center;padding:75px 24px}.locSeoFinal h2{font-size:clamp(34px,5vw,52px);margin:12px}.locSeoFinal .locSeoActions{justify-content:center}@media(max-width:850px){.locSeoHeroGrid{grid-template-columns:1fr}.locSeoGrid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.locSeoHero{padding:58px 24px}.locSeoHero h1{font-size:41px}.locSeoGrid{grid-template-columns:1fr}.locSeoSection{margin:65px auto}}
`}</style>
 </main>
}
