import type { MetadataRoute } from "next";

const BASE_URL = "https://www.mioseg-qr.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    "/de",
    "/de/explore",
    "/de/get-app",
    "/de/hilfe",
    "/de/qr-code-scanner",
    "/de/qr-code-generator",
    "/de/dynamischer-qr-code",
    "/de/business-qr-code",
    "/en",
    "/en/explore",
    "/en/get-app",
    "/en/help",
    "/en/qr-code-scanner",
    "/en/qr-code-generator",
    "/en/dynamic-qr-code",
    "/en/business-qr-code",
    "/tr",
    "/tr/explore",
    "/tr/get-app",
    "/tr/yardim",
    "/tr/qr-kod-tarayici",
    "/tr/qr-kod-olusturucu",
    "/tr/dinamik-qr-kod",
    "/tr/business-qr-code",
    "/pl",
    "/pl/explore",
    "/pl/get-app",
    "/pl/pomoc",
    "/pl/skaner-kodow-qr",
    "/pl/generator-kodow-qr",
    "/pl/dynamiczny-kod-qr",
    "/pl/business-qr-code",
    "/ar",
    "/ar/explore",
    "/ar/get-app",
    "/ar/help",
    "/ar/qr-code-scanner",
    "/ar/qr-code-generator",
    "/ar/dynamic-qr-code",
    "/ar/business-qr-code",
    "/fr",
    "/fr/explore",
    "/fr/get-app",
    "/fr/aide",
    "/fr/scanner-qr-code",
    "/fr/generateur-qr-code",
    "/fr/qr-code-dynamique",
    "/fr/qr-code-business",
    "/es",
    "/es/explore",
    "/es/get-app",
    "/es/ayuda",
    "/es/escaner-codigo-qr",
    "/es/generador-codigo-qr",
    "/es/codigo-qr-dinamico",
    "/es/codigo-qr-business",
    "/it",
    "/it/explore",
    "/it/get-app",
    "/it/aiuto",
    "/it/scanner-codice-qr",
    "/it/generatore-codice-qr",
    "/it/codice-qr-dinamico",
    "/it/business-qr-code",
  ];

  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    changeFrequency: route.endsWith("/explore") ? "daily" : "weekly",
    priority: route.split("/").filter(Boolean).length === 1 ? 1 : 0.8,
  }));
}
